### ISSUE TITLE
和IOS浏览器滑动返回的冲突问题

### ISSUE THREAD

**Issue by tuweifu** [RedTeapot/Viewjs#4]
很早之前就像找个这样的JS框架了，终于看见有大神开发了。哈哈
期待滑动返回上一视图这样的功能。
在IOS浏览器上，由于侧边往右滑动是浏览器默认返回上一页的手势（应该是会触发返回按键），这时候页面会有一个IOS浏览器自带的滑动切换的动画，而自带的滑动动画结束后，由于是返回了上一页，此时 VIEW.JS 也会执行一次返回上一页的滑动动画。这就导致了有两个滑动切换的动画。

**Comment by RedTeapot** [comment]
感谢你的使用和反馈，我会尽快检查这一问题，届时回复你。
由于年尾将至，工作有些繁忙，所以可能不会太快，但也不会让你等待太久。
另，View.js 的使用文档重新梳理了一番，你可以到这里查阅。如果有什么意见，尽可以想我反馈。


祝好！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"tuweifu"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月3日(星期二) 下午5:50
收件人:&nbsp;"RedTeapot/Viewjs"<Viewjs@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[RedTeapot/Viewjs] 和IOS浏览器滑动返回的冲突问题 (#4)




很早之前就像找个这样的JS框架了，终于看见有大神开发了。哈哈
 期待滑动返回上一视图这样的功能。
 在IOS浏览器上，由于侧边往右滑动是浏览器默认返回上一页的手势（应该是会触发返回按键），这时候页面会有一个IOS浏览器自带的滑动切换的动画，而自带的滑动动画结束后，由于是返回了上一页，此时 VIEW.JS 也会执行一次返回上一页的滑动动画。这就导致了有两个滑动切换的动画。

**Comment by RedTeapot** [comment]
感谢你的使用和反馈，我会尽快检查这一问题，届时回复你。
由于年尾将至，工作有些繁忙，所以可能不会太快，但也不会让你等待太久。
另，View.js 的使用文档重新梳理了一番，你可以到 https://doc.view-js.com/ 查阅。如果有什么意见，尽可以向我反馈。


祝好！




------------------ 原始邮件 ------------------
发件人:&nbsp;"tuweifu"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月3日(星期二) 下午5:50
收件人:&nbsp;"RedTeapot/Viewjs"<Viewjs@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[RedTeapot/Viewjs] 和IOS浏览器滑动返回的冲突问题 (#4)




很早之前就像找个这样的JS框架了，终于看见有大神开发了。哈哈
 期待滑动返回上一视图这样的功能。
 在IOS浏览器上，由于侧边往右滑动是浏览器默认返回上一页的手势（应该是会触发返回按键），这时候页面会有一个IOS浏览器自带的滑动切换的动画，而自带的滑动动画结束后，由于是返回了上一页，此时 VIEW.JS 也会执行一次返回上一页的滑动动画。这就导致了有两个滑动切换的动画。

**Comment by tuweifu** [comment]
谢谢你的回复 :)，我将在接下去一个项目中使用 view.js 详细看了文档，应该很好用。

**Comment by RedTeapot** [comment]
1. 滑动返回/前进，是safari自带的特性，无法禁止；
2. 浏览器执行的前进或后退，无法区分是通过滑动手势触发的，还是通过点击底部按钮触发的；
3. 借助下一版本的 View.js，开发者可以区分 “由应用驱动的切换” 和 “由浏览器驱动的切换”，届时可以在“切换动作由浏览器驱动”场景下不呈现动画，而在“切换动作由应用驱动”的场景下呈现动画。例如：[视图切换动画](http://www.view-js.com/demo/view-switch-animation/2/)
